reload("user/plugins/builtin/null-ls")
reload("user/plugins/builtin/nvimtree")
reload("user/plugins/builtin/whichkey")
reload("user/plugins/builtin/telescope")
reload("user/plugins/builtin/lspconfig")
