#!/usr/bin/env bash


DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty
echo 'SimLink created: Kitty'

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
echo 'SimLink created: Nvim'

rm -rf $HOME/.config/lvim
ln -s $DOTFILES/lvim $HOME/.config/lvim
echo 'SimLink created: Lvim'
