#!/usr/bin/env bash


DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty
echo 'SimLink created: Kitty'

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf
echo 'SimLink created: Tmux'


mkdir -p $HOME/.local/bin
rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t
echo 'SimLink created: Tmux scripts'

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
echo 'SimLink created: Nvim'

rm -rf $HOME/.config/lvim
ln -s $DOTFILES/lvim $HOME/.config/lvim
echo 'SimLink created: Lvim'
